# Small local network of three nodes using the fastest mean16
version: '3'
services:
  node1:
    image: aeternity/aeternity:v5.0.2
    hostname: node1
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
       bin/aeternity console -noinput -aehttp enable_debug_endpoints true
    volumes:
      - ./docker/aeternity_node1_mean15.yaml:/home/aeternity/aeternity.yaml
      - ./docker/keys/node1:/home/aeternity/node/keys

  node2:
    image: aeternity/aeternity:v5.0.2
    hostname: node2
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
       bin/aeternity console -noinput -aehttp enable_debug_endpoints true
    volumes:
      - ./docker/aeternity_node2_mean15.yaml:/home/aeternity/aeternity.yaml
      - ./docker/keys/node2:/home/aeternity/node/keys

  node3:
    image: aeternity/aeternity:v5.0.2
    hostname: node3
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
       bin/aeternity console -noinput -aehttp enable_debug_endpoints true
    volumes:
      - ./docker/aeternity_node3_mean15.yaml:/home/aeternity/aeternity.yaml
      - ./docker/keys/node3:/home/aeternity/node/keys

  proxy:
    image: nginx:1.13.8
    hostname: proxy
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"

    volumes:
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx-cors.conf:/etc/nginx/cors.conf
      - ./docker/nginx-ws.conf:/etc/nginx/ws.conf

  

volumes:
  node1_db:
  node1_keys:
  node2_db:
  node2_keys:
  node3_db:
  node3_keys:
    